/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

`DEFINE_FP_INSTRUCTION(FLW,       I_FORMAT, LOAD, RV32F)
`DEFINE_FP_INSTRUCTION(FSW,       S_FORMAT, STORE, RV32F)
`DEFINE_FP_INSTRUCTION(FMADD_S,   R4_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FMSUB_S,   R4_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FNMSUB_S,  R4_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FNMADD_S,  R4_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FADD_S,    R_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FSUB_S,    R_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FMUL_S,    R_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FDIV_S,    R_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FSQRT_S,   I_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FSGNJ_S,   R_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FSGNJN_S,  R_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FSGNJX_S,  R_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FMIN_S,    R_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FMAX_S,    R_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FCVT_W_S,  I_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FCVT_WU_S, I_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FMV_X_W,   I_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FEQ_S,     R_FORMAT, COMPARE, RV32F)
`DEFINE_FP_INSTRUCTION(FLT_S,     R_FORMAT, COMPARE, RV32F)
`DEFINE_FP_INSTRUCTION(FLE_S,     R_FORMAT, COMPARE, RV32F)
`DEFINE_FP_INSTRUCTION(FCLASS_S,  R_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FCVT_S_W,  I_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FCVT_S_WU, I_FORMAT, ARITHMETIC, RV32F)
`DEFINE_FP_INSTRUCTION(FMV_W_X,   I_FORMAT, ARITHMETIC, RV32F)
