/*
 * Copyright 2020 Google LLC
 * Copyright 2020 Andes Technology Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Tensor CSR access instruction
`DEFINE_INSTRUCTION(YSETVLI,    VSET_FORMAT, CSR, RVY)
`DEFINE_INSTRUCTION(YSETVL,     VSET_FORMAT, CSR, RVY)

// Tensor integer arithmetic instruction
`DEFINE_YA_INSTRUCTION(YADD,     YA_FORMAT, ARITHMETIC, RVY, {YY, YX, YI})
`DEFINE_YA_INSTRUCTION(YSUB,     YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YRSUB,    YA_FORMAT, ARITHMETIC, RVY, {YX, YI})
`DEFINE_YA_INSTRUCTION(YWADDU,   YA_FORMAT, ARITHMETIC, RVY, {YY, YX, WV, WX})
`DEFINE_YA_INSTRUCTION(YWSUBU,   YA_FORMAT, ARITHMETIC, RVY, {YY, YX, WV, WX})
`DEFINE_YA_INSTRUCTION(YWADD,    YA_FORMAT, ARITHMETIC, RVY, {YY, YX, WV, WX})
`DEFINE_YA_INSTRUCTION(YWSUB,    YA_FORMAT, ARITHMETIC, RVY, {YY, YX, WV, WX})
`DEFINE_YA_INSTRUCTION(YADC,     YA_FORMAT, ARITHMETIC, RVY, {YYM, YXM, YIM})
`DEFINE_YA_INSTRUCTION(YMADC,    YA_FORMAT, ARITHMETIC, RVY, {YYM, YXM, YIM, YY, YX, YI})
`DEFINE_YA_INSTRUCTION(YSBC,     YA_FORMAT, ARITHMETIC, RVY, {YYM, YXM})
`DEFINE_YA_INSTRUCTION(YMSBC,    YA_FORMAT, ARITHMETIC, RVY, {YYM, YXM, YY, YX})
`DEFINE_YA_INSTRUCTION(YAND,     YA_FORMAT, ARITHMETIC, RVY, {YY, YX, YI})
`DEFINE_YA_INSTRUCTION(YOR,      YA_FORMAT, ARITHMETIC, RVY, {YY, YX, YI})
`DEFINE_YA_INSTRUCTION(YXOR,     YA_FORMAT, ARITHMETIC, RVY, {YY, YX, YI})
`DEFINE_YA_INSTRUCTION(YSLL,     YA_FORMAT, SHIFT, RVY, {YY, YX, YI})
`DEFINE_YA_INSTRUCTION(YSRL,     YA_FORMAT, SHIFT, RVY, {YY, YX, YI})
`DEFINE_YA_INSTRUCTION(YSRA,     YA_FORMAT, SHIFT, RVY, {YY, YX, YI})
`DEFINE_YA_INSTRUCTION(YNSRL,    YA_FORMAT, SHIFT, RVY, {WV, WX, WI})
`DEFINE_YA_INSTRUCTION(YNSRA,    YA_FORMAT, SHIFT, RVY, {WV, WX, WI})
`DEFINE_YA_INSTRUCTION(YMSEQ,    YA_FORMAT, COMPARE, RVY, {YY, YX, YI})
`DEFINE_YA_INSTRUCTION(YMSNE,    YA_FORMAT, COMPARE, RVY, {YY, YX, YI})
`DEFINE_YA_INSTRUCTION(YMSLTU,   YA_FORMAT, COMPARE, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YMSLT,    YA_FORMAT, COMPARE, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YMSLEU,   YA_FORMAT, COMPARE, RVY, {YY, YX, YI})
`DEFINE_YA_INSTRUCTION(YMSLE,    YA_FORMAT, COMPARE, RVY, {YY, YX, YI})
`DEFINE_YA_INSTRUCTION(YMSGTU,   YA_FORMAT, COMPARE, RVY, {YX, YI})
`DEFINE_YA_INSTRUCTION(YMSGT,    YA_FORMAT, COMPARE, RVY, {YX, YI})
`DEFINE_YA_INSTRUCTION(YMINU,    YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YMIN,     YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YMAXU,    YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YMAX,     YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YMUL,     YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YMULH,    YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YMULHU,   YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YMULHSU,  YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YDIVU,    YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YDIV,     YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YREMU,    YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YREM,     YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YWMUL,    YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YWMULU,   YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YWMULSU,  YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YMACC,    YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YNMSAC,   YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YMADD,    YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YNMSUB,   YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YWMACCU,  YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YWMACC,   YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YWMACCSU, YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YWMACCUS, YA_FORMAT, ARITHMETIC, RVY, {YX})
/* Quad widening is not yet supported
`DEFINE_YA_INSTRUCTION(YQMACCU,  YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YQMACC,   YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YQMACCSU, YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YQMACCUS, YA_FORMAT, ARITHMETIC, RVY, {YX})
*/
`DEFINE_YA_INSTRUCTION(YMERGE,   YA_FORMAT, ARITHMETIC, RVY, {YYM, YXM, YIM})
`DEFINE_YA_INSTRUCTION(YMV,      YA_FORMAT, ARITHMETIC, RVY, {YY, YX, YI})

// Tensor Fixed-Point Arithmetic Instructions
`DEFINE_YA_INSTRUCTION(YSADDU,   YA_FORMAT, ARITHMETIC, RVY, {YY, YX, YI})
`DEFINE_YA_INSTRUCTION(YSADD,    YA_FORMAT, ARITHMETIC, RVY, {YY, YX, YI})
`DEFINE_YA_INSTRUCTION(YSSUBU,   YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YSSUB,    YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YAADDU,   YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YAADD,    YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YASUBU,   YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YASUB,    YA_FORMAT, ARITHMETIC, RVY, {YY, YX})
`DEFINE_YA_INSTRUCTION(YSSRL,    YA_FORMAT, SHIFT, RVY, {YY, YX, YI})
`DEFINE_YA_INSTRUCTION(YSSRA,    YA_FORMAT, SHIFT, RVY, {YY, YX, YI})
`DEFINE_YA_INSTRUCTION(YNCLIPU,  YA_FORMAT, ARITHMETIC, RVY, {WV, WX, WI})
`DEFINE_YA_INSTRUCTION(YNCLIP,   YA_FORMAT, ARITHMETIC, RVY, {WV, WX, WI})

// Tensor Floating-Point Instructions
`DEFINE_YA_INSTRUCTION(YFADD,    YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFSUB,    YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFRSUB,   YA_FORMAT, ARITHMETIC, RVY, {VF})
`DEFINE_YA_INSTRUCTION(YFMUL,    YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFDIV,    YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFRDIV,   YA_FORMAT, ARITHMETIC, RVY, {VF})
`DEFINE_YA_INSTRUCTION(YFWMUL,   YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFMACC,   YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFNMACC,  YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFMSAC,   YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFNMSAC,  YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFMADD,   YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFNMADD,  YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFMSUB,   YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFNMSUB,  YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFWMACC,  YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFWNMACC, YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFWMSAC,  YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFWNMSAC, YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFSQRT_Y, VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFMIN,    YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFMAX,    YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFSGNJ,   YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFSGNJN,  YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YFSGNJX,  YA_FORMAT, ARITHMETIC, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YMFEQ,    YA_FORMAT, COMPARE, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YMFNE,    YA_FORMAT, COMPARE, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YMFLT,    YA_FORMAT, COMPARE, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YMFLE,    YA_FORMAT, COMPARE, RVY, {YY, VF})
`DEFINE_YA_INSTRUCTION(YMFGT,    YA_FORMAT, COMPARE, RVY, {VF})
`DEFINE_YA_INSTRUCTION(YMFGE,    YA_FORMAT, COMPARE, RVY, {VF})
`DEFINE_YA_INSTRUCTION(YFCLASS_Y,VS2_FORMAT, COMPARE, RVY)
`DEFINE_YA_INSTRUCTION(YFMERGE,  YA_FORMAT, ARITHMETIC, RVY, {VFM})
`DEFINE_YA_INSTRUCTION(YFMV,     YA_FORMAT, ARITHMETIC, RVY, {VF})

// Tensor conversion instructions
`DEFINE_YA_INSTRUCTION(YFCVT_XU_F_Y,     VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFCVT_X_F_Y,      VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFCVT_F_XU_Y,     VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFCVT_F_X_Y,      VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFWCVT_XU_F_Y,    VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFWCVT_X_F_Y,     VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFWCVT_F_XU_Y,    VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFWCVT_F_X_Y,     VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFWCVT_F_F_Y,     VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFNCVT_XU_F_W,    VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFNCVT_X_F_W,     VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFNCVT_F_XU_W,    VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFNCVT_F_X_W,     VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFNCVT_F_F_W,     VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFNCVT_ROD_F_F_W, VS2_FORMAT, ARITHMETIC, RVY)

// Tensor reduction instruction
`DEFINE_YA_INSTRUCTION(YREDSUM_YS,    YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YREDMAXU_YS,   YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YREDMAX_YS,    YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YREDMINU_YS,   YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YREDMIN_YS,    YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YREDAND_YS,    YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YREDOR_YS,     YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YREDXOR_YS,    YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YWREDSUMU_YS,  YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YWREDSUM_YS,   YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFREDOSUM_YS,  YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFREDSUM_YS,   YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFREDMAX_YS,   YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFWREDOSUM_YS, YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFWREDSUM_YS,  YA_FORMAT, ARITHMETIC, RVY)

// Tensor mask instruction
`DEFINE_YA_INSTRUCTION(YMAND_MM,    YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YMNAND_MM,   YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YMANDNOT_MM, YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YMXOR_MM,    YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YMOR_MM,     YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YMNOR_MM,    YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YMORNOT_MM,  YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YMXNOR_MM,   YA_FORMAT, ARITHMETIC, RVY)

`DEFINE_YA_INSTRUCTION(YPOPC_M,   VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFIRST_M,  VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YMSBF_M,   VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YMSIF_M,   VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YMSOF_M,   VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YIOTA_M,   VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YID_Y,     VS2_FORMAT, ARITHMETIC, RVY)

// Tensor permutation instruction
`DEFINE_YA_INSTRUCTION(YMV_X_S,  YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YMV_S_X,  YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFMV_F_S, YA_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YFMV_S_F, YA_FORMAT, ARITHMETIC, RVY)

`DEFINE_YA_INSTRUCTION(YSLIDEUP,    YA_FORMAT, ARITHMETIC, RVY, {YI,YX})
`DEFINE_YA_INSTRUCTION(YSLIDEDOWN,  YA_FORMAT, ARITHMETIC, RVY, {YI,YX})
`DEFINE_YA_INSTRUCTION(YSLIDE1UP,   YA_FORMAT, ARITHMETIC, RVY, {YX})
`DEFINE_YA_INSTRUCTION(YSLIDE1DOWN, YA_FORMAT, ARITHMETIC, RVY, {YX})
`DEFINE_YA_INSTRUCTION(YRGATHER,    YA_FORMAT, ARITHMETIC, RVY, {YY,YX,YI})
`DEFINE_YA_INSTRUCTION(YCOMPRESS,   YA_FORMAT, ARITHMETIC, RVY, {VM})

`DEFINE_YA_INSTRUCTION(YMV1R_Y, VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YMV2R_Y, VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YMV4R_Y, VS2_FORMAT, ARITHMETIC, RVY)
`DEFINE_YA_INSTRUCTION(YMV8R_Y, VS2_FORMAT, ARITHMETIC, RVY)

// -------------------------------------------------------------------------
//  Section 7. Tensor Loads and Stores
// -------------------------------------------------------------------------
// Section 7.4 - Tensor Unit-Stride Instructions
`DEFINE_YA_INSTRUCTION(YLE_Y, VL_FORMAT, LOAD, RVY)
`DEFINE_YA_INSTRUCTION(YSE_Y, VS_FORMAT, STORE, RVY)
// Section 7.5 - Tensor Strided Instructions
`DEFINE_YA_INSTRUCTION(YLSE_Y, VLS_FORMAT, LOAD, RVY)
`DEFINE_YA_INSTRUCTION(YSSE_Y, VSS_FORMAT, STORE, RVY)
// Section 7.6 - Tensor Indexed Instructions
`DEFINE_YA_INSTRUCTION(YLXEI_Y, VLX_FORMAT, LOAD, RVY)
`DEFINE_YA_INSTRUCTION(YSXEI_Y, VSX_FORMAT, STORE, RVY)
`DEFINE_YA_INSTRUCTION(YSUXEI_Y, VSX_FORMAT, STORE, RVY)
// Section 7.7 - Tensor Unit-Stride Fault-Only-First Loads
`DEFINE_YA_INSTRUCTION(YLEFF_Y, VL_FORMAT, LOAD, RVY)
// Section 7.8 - Tensor Load/Store Segment Instructions (Zylsseg)
// 7.8.1. Tensor Unit Strided Segment Loads and Stores
`DEFINE_YA_INSTRUCTION(YLSEGE_Y, VL_FORMAT, LOAD, RVY, {}, "zylsseg")
`DEFINE_YA_INSTRUCTION(YSSEGE_Y, VS_FORMAT, STORE, RVY, {}, "zylsseg")
`DEFINE_YA_INSTRUCTION(YLSEGEFF_Y, VL_FORMAT, LOAD, RVY, {}, "zylsseg")
// 7.8.2. Tensor Strided Segment Loads and Stores
`DEFINE_YA_INSTRUCTION(YLSSEGE_Y, VLS_FORMAT, LOAD, RVY, {}, "zylsseg")
`DEFINE_YA_INSTRUCTION(YSSSEGE_Y, VSS_FORMAT, STORE, RVY, {}, "zylsseg")
// 7.8.3. Tensor Indexed Segment Loads and Stores
`DEFINE_YA_INSTRUCTION(YLXSEGEI_Y, VLX_FORMAT, LOAD, RVY, {}, "zylsseg")
`DEFINE_YA_INSTRUCTION(YSXSEGEI_Y, VSX_FORMAT, STORE, RVY, {}, "zylsseg")
`DEFINE_YA_INSTRUCTION(YSUXSEGEI_Y, VSX_FORMAT, STORE, RVY, {}, "zylsseg")

// -------------------------------------------------------------------------
//  Section 8. Tensor AMO Operations (Zvamo)
// -------------------------------------------------------------------------
// EEW tensor AMOs
`DEFINE_YA_INSTRUCTION(YAMOSWAPE_Y, VAMO_FORMAT, AMO, RVY, {}, "zyamo")
`DEFINE_YA_INSTRUCTION(YAMOADDE_Y, VAMO_FORMAT, AMO, RVY, {}, "zyamo")
`DEFINE_YA_INSTRUCTION(YAMOXORE_Y, VAMO_FORMAT, AMO, RVY, {}, "zyamo")
`DEFINE_YA_INSTRUCTION(YAMOANDE_Y, VAMO_FORMAT, AMO, RVY, {}, "zyamo")
`DEFINE_YA_INSTRUCTION(YAMOORE_Y, VAMO_FORMAT, AMO, RVY, {}, "zyamo")
`DEFINE_YA_INSTRUCTION(YAMOMINE_Y, VAMO_FORMAT, AMO, RVY, {}, "zyamo")
`DEFINE_YA_INSTRUCTION(YAMOMAXE_Y, VAMO_FORMAT, AMO, RVY, {}, "zyamo")
`DEFINE_YA_INSTRUCTION(YAMOMINUE_Y, VAMO_FORMAT, AMO, RVY, {}, "zyamo")
`DEFINE_YA_INSTRUCTION(YAMOMAXUE_Y, VAMO_FORMAT, AMO, RVY, {}, "zyamo")
