/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// LOAD instructions
`DEFINE_INSTRUCTION(LB,     I_FORMAT, LOAD, RV32I)
`DEFINE_INSTRUCTION(LH,     I_FORMAT, LOAD, RV32I)
`DEFINE_INSTRUCTION(LW,     I_FORMAT, LOAD, RV32I)
`DEFINE_INSTRUCTION(LBU,    I_FORMAT, LOAD, RV32I)
`DEFINE_INSTRUCTION(LHU,    I_FORMAT, LOAD, RV32I)
// STORE instructions
`DEFINE_INSTRUCTION(SB,     S_FORMAT, STORE, RV32I)
`DEFINE_INSTRUCTION(SH,     S_FORMAT, STORE, RV32I)
`DEFINE_INSTRUCTION(SW,     S_FORMAT, STORE, RV32I)
// SHIFT intructions
`DEFINE_INSTRUCTION(SLL,    R_FORMAT, SHIFT, RV32I)
`DEFINE_INSTRUCTION(SLLI,   I_FORMAT, SHIFT, RV32I)
`DEFINE_INSTRUCTION(SRL,    R_FORMAT, SHIFT, RV32I)
`DEFINE_INSTRUCTION(SRLI,   I_FORMAT, SHIFT, RV32I)
`DEFINE_INSTRUCTION(SRA,    R_FORMAT, SHIFT, RV32I)
`DEFINE_INSTRUCTION(SRAI,   I_FORMAT, SHIFT, RV32I)
// ARITHMETIC intructions
`DEFINE_INSTRUCTION(ADD,    R_FORMAT, ARITHMETIC, RV32I)
`DEFINE_INSTRUCTION(ADDI,   I_FORMAT, ARITHMETIC, RV32I)
`DEFINE_INSTRUCTION(NOP,    I_FORMAT, ARITHMETIC, RV32I)
`DEFINE_INSTRUCTION(SUB,    R_FORMAT, ARITHMETIC, RV32I)
`DEFINE_INSTRUCTION(LUI,    U_FORMAT, ARITHMETIC, RV32I, UIMM)
`DEFINE_INSTRUCTION(AUIPC,  U_FORMAT, ARITHMETIC, RV32I, UIMM)
// LOGICAL instructions
`DEFINE_INSTRUCTION(XOR,    R_FORMAT, LOGICAL, RV32I)
`DEFINE_INSTRUCTION(XORI,   I_FORMAT, LOGICAL, RV32I)
`DEFINE_INSTRUCTION(OR,     R_FORMAT, LOGICAL, RV32I)
`DEFINE_INSTRUCTION(ORI,    I_FORMAT, LOGICAL, RV32I)
`DEFINE_INSTRUCTION(AND,    R_FORMAT, LOGICAL, RV32I)
`DEFINE_INSTRUCTION(ANDI,   I_FORMAT, LOGICAL, RV32I)
// COMPARE instructions
`DEFINE_INSTRUCTION(SLT,    R_FORMAT, COMPARE, RV32I)
`DEFINE_INSTRUCTION(SLTI,   I_FORMAT, COMPARE, RV32I)
`DEFINE_INSTRUCTION(SLTU,   R_FORMAT, COMPARE, RV32I)
`DEFINE_INSTRUCTION(SLTIU,  I_FORMAT, COMPARE, RV32I)
// BRANCH instructions
`DEFINE_INSTRUCTION(BEQ,    B_FORMAT, BRANCH, RV32I)
`DEFINE_INSTRUCTION(BNE,    B_FORMAT, BRANCH, RV32I)
`DEFINE_INSTRUCTION(BLT,    B_FORMAT, BRANCH, RV32I)
`DEFINE_INSTRUCTION(BGE,    B_FORMAT, BRANCH, RV32I)
`DEFINE_INSTRUCTION(BLTU,   B_FORMAT, BRANCH, RV32I)
`DEFINE_INSTRUCTION(BGEU,   B_FORMAT, BRANCH, RV32I)
// JUMP instructions
`DEFINE_INSTRUCTION(JAL,    J_FORMAT, JUMP, RV32I)
`DEFINE_INSTRUCTION(JALR,   I_FORMAT, JUMP, RV32I)
// SYNCH instructions
`DEFINE_INSTRUCTION(FENCE,  I_FORMAT, SYNCH, RV32I)
`DEFINE_INSTRUCTION(FENCE_I, I_FORMAT, SYNCH, RV32I)
`DEFINE_INSTRUCTION(SFENCE_VMA, R_FORMAT, SYNCH, RV32I)
// SYSTEM instructions
`DEFINE_INSTRUCTION(ECALL,   I_FORMAT, SYSTEM, RV32I)
`DEFINE_INSTRUCTION(EBREAK,  I_FORMAT, SYSTEM, RV32I)
`DEFINE_INSTRUCTION(URET,    I_FORMAT, SYSTEM, RV32I)
`DEFINE_INSTRUCTION(SRET,    I_FORMAT, SYSTEM, RV32I)
`DEFINE_INSTRUCTION(MRET,    I_FORMAT, SYSTEM, RV32I)
`DEFINE_INSTRUCTION(DRET,    I_FORMAT, SYSTEM, RV32I)
`DEFINE_INSTRUCTION(WFI,     I_FORMAT, INTERRUPT, RV32I)
// CSR instructions
`DEFINE_CSR_INSTRUCTION(CSRRW,  R_FORMAT, CSR, RV32I, UIMM)
`DEFINE_CSR_INSTRUCTION(CSRRS,  R_FORMAT, CSR, RV32I, UIMM)
`DEFINE_CSR_INSTRUCTION(CSRRC,  R_FORMAT, CSR, RV32I, UIMM)
`DEFINE_CSR_INSTRUCTION(CSRRWI, I_FORMAT, CSR, RV32I, UIMM)
`DEFINE_CSR_INSTRUCTION(CSRRSI, I_FORMAT, CSR, RV32I, UIMM)
`DEFINE_CSR_INSTRUCTION(CSRRCI, I_FORMAT, CSR, RV32I, UIMM)
