/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

`DEFINE_FP_INSTRUCTION(FLD,       I_FORMAT, LOAD, RV32D)
`DEFINE_FP_INSTRUCTION(FSD,       S_FORMAT, STORE, RV32D)
`DEFINE_FP_INSTRUCTION(FMADD_D,   R4_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FMSUB_D,   R4_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FNMSUB_D,  R4_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FNMADD_D,  R4_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FADD_D,    R_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FSUB_D,    R_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FMUL_D,    R_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FDIV_D,    R_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FSQRT_D,   I_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FSGNJ_D,   R_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FSGNJN_D,  R_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FSGNJX_D,  R_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FMIN_D,    R_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FMAX_D,    R_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FCVT_S_D,  I_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FCVT_D_S,  I_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FEQ_D,     R_FORMAT, COMPARE, RV32D)
`DEFINE_FP_INSTRUCTION(FLT_D,     R_FORMAT, COMPARE, RV32D)
`DEFINE_FP_INSTRUCTION(FLE_D,     R_FORMAT, COMPARE, RV32D)
`DEFINE_FP_INSTRUCTION(FCLASS_D,  R_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FCVT_W_D,  I_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FCVT_WU_D, I_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FCVT_D_W,  I_FORMAT, ARITHMETIC, RV32D)
`DEFINE_FP_INSTRUCTION(FCVT_D_WU, I_FORMAT, ARITHMETIC, RV32D)
