/*
 * Copyright 2020 Google LLC
 * Copyright 2020 Andes Technology Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Matrix CSR access instruction
`DEFINE_INSTRUCTION(WSETWLI,    WSET_FORMAT, CSR, RVW)
`DEFINE_INSTRUCTION(WSETWL,     WSET_FORMAT, CSR, RVW)

// Matrix integer arithmetic instruction
`DEFINE_WA_INSTRUCTION(WADD,     WA_FORMAT, ARITHMETIC, RVW, {WW, WX, VI})
`DEFINE_WA_INSTRUCTION(WSUB,     WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WRSUB,    WA_FORMAT, ARITHMETIC, RVW, {WX, VI})
`DEFINE_WA_INSTRUCTION(WWADDU,   WA_FORMAT, ARITHMETIC, RVW, {WW, WX, WV, WX})
`DEFINE_WA_INSTRUCTION(WWSUBU,   WA_FORMAT, ARITHMETIC, RVW, {WW, WX, WV, WX})
`DEFINE_WA_INSTRUCTION(WWADD,    WA_FORMAT, ARITHMETIC, RVW, {WW, WX, WV, WX})
`DEFINE_WA_INSTRUCTION(WWSUB,    WA_FORMAT, ARITHMETIC, RVW, {WW, WX, WV, WX})
`DEFINE_WA_INSTRUCTION(WADC,     WA_FORMAT, ARITHMETIC, RVW, {WWM, WXM, VIM})
`DEFINE_WA_INSTRUCTION(WMADC,    WA_FORMAT, ARITHMETIC, RVW, {WWM, WXM, VIM, WW, WX, VI})
`DEFINE_WA_INSTRUCTION(WSBC,     WA_FORMAT, ARITHMETIC, RVW, {WWM, WXM})
`DEFINE_WA_INSTRUCTION(WMSBC,    WA_FORMAT, ARITHMETIC, RVW, {WWM, WXM, WW, WX})
`DEFINE_WA_INSTRUCTION(WAND,     WA_FORMAT, ARITHMETIC, RVW, {WW, WX, VI})
`DEFINE_WA_INSTRUCTION(WOR,      WA_FORMAT, ARITHMETIC, RVW, {WW, WX, VI})
`DEFINE_WA_INSTRUCTION(WXOR,     WA_FORMAT, ARITHMETIC, RVW, {WW, WX, VI})
`DEFINE_WA_INSTRUCTION(WSLL,     WA_FORMAT, SHIFT, RVW, {WW, WX, VI})
`DEFINE_WA_INSTRUCTION(WSRL,     WA_FORMAT, SHIFT, RVW, {WW, WX, VI})
`DEFINE_WA_INSTRUCTION(WSRA,     WA_FORMAT, SHIFT, RVW, {WW, WX, VI})
`DEFINE_WA_INSTRUCTION(WNSRL,    WA_FORMAT, SHIFT, RVW, {WV, WX, WI})
`DEFINE_WA_INSTRUCTION(WNSRA,    WA_FORMAT, SHIFT, RVW, {WV, WX, WI})
`DEFINE_WA_INSTRUCTION(WMSEQ,    WA_FORMAT, COMPARE, RVW, {WW, WX, VI})
`DEFINE_WA_INSTRUCTION(WMSNE,    WA_FORMAT, COMPARE, RVW, {WW, WX, VI})
`DEFINE_WA_INSTRUCTION(WMSLTU,   WA_FORMAT, COMPARE, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WMSLT,    WA_FORMAT, COMPARE, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WMSLEU,   WA_FORMAT, COMPARE, RVW, {WW, WX, VI})
`DEFINE_WA_INSTRUCTION(WMSLE,    WA_FORMAT, COMPARE, RVW, {WW, WX, VI})
`DEFINE_WA_INSTRUCTION(WMSGTU,   WA_FORMAT, COMPARE, RVW, {WX, VI})
`DEFINE_WA_INSTRUCTION(WMSGT,    WA_FORMAT, COMPARE, RVW, {WX, VI})
`DEFINE_WA_INSTRUCTION(WMINU,    WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WMIN,     WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WMAXU,    WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WMAX,     WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WMUL,     WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WMULH,    WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WMULHU,   WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WMULHSU,  WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WDIVU,    WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WDIV,     WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WREMU,    WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WREM,     WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WWMUL,    WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WWMULU,   WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WWMULSU,  WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WMACC,    WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WNMSAC,   WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WMADD,    WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WNMSUB,   WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WWMACCU,  WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WWMACC,   WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WWMACCSU, WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WWMACCUS, WA_FORMAT, ARITHMETIC, RVW, {WX})
/* Quad widening is not yet supported
`DEFINE_WA_INSTRUCTION(WQMACCU,  WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WQMACC,   WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WQMACCSU, WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WQMACCUS, WA_FORMAT, ARITHMETIC, RVW, {WX})
*/
`DEFINE_WA_INSTRUCTION(WMERGE,   WA_FORMAT, ARITHMETIC, RVW, {WWM, WXM, VIM})
`DEFINE_WA_INSTRUCTION(WMV,      WA_FORMAT, ARITHMETIC, RVW, {WW, WX, VI})

// Matrix Fixed-Point Arithmetic Instructions
`DEFINE_WA_INSTRUCTION(WSADDU,   WA_FORMAT, ARITHMETIC, RVW, {WW, WX, VI})
`DEFINE_WA_INSTRUCTION(WSADD,    WA_FORMAT, ARITHMETIC, RVW, {WW, WX, VI})
`DEFINE_WA_INSTRUCTION(WSSUBU,   WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WSSUB,    WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WAADDU,   WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WAADD,    WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WASUBU,   WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WASUB,    WA_FORMAT, ARITHMETIC, RVW, {WW, WX})
`DEFINE_WA_INSTRUCTION(WSSRL,    WA_FORMAT, SHIFT, RVW, {WW, WX, VI})
`DEFINE_WA_INSTRUCTION(WSSRA,    WA_FORMAT, SHIFT, RVW, {WW, WX, VI})
`DEFINE_WA_INSTRUCTION(WNCLIPU,  WA_FORMAT, ARITHMETIC, RVW, {WV, WX, WI})
`DEFINE_WA_INSTRUCTION(WNCLIP,   WA_FORMAT, ARITHMETIC, RVW, {WV, WX, WI})

// Matrix Floating-Point Instructions
`DEFINE_WA_INSTRUCTION(WFADD,    WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFSUB,    WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFRSUB,   WA_FORMAT, ARITHMETIC, RVW, {WF})
`DEFINE_WA_INSTRUCTION(WFMUL,    WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFDIV,    WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFRDIV,   WA_FORMAT, ARITHMETIC, RVW, {WF})
`DEFINE_WA_INSTRUCTION(WFWMUL,   WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFMACC,   WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFNMACC,  WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFMSAC,   WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFNMSAC,  WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFMADD,   WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFNMADD,  WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFMSUB,   WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFNMSUB,  WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFWMACC,  WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFWNMACC, WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFWMSAC,  WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFWNMSAC, WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFSQRT_W, WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFMIN,    WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFMAX,    WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFSGNJ,   WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFSGNJN,  WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WFSGNJX,  WA_FORMAT, ARITHMETIC, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WMFEQ,    WA_FORMAT, COMPARE, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WMFNE,    WA_FORMAT, COMPARE, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WMFLT,    WA_FORMAT, COMPARE, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WMFLE,    WA_FORMAT, COMPARE, RVW, {WW, WF})
`DEFINE_WA_INSTRUCTION(WMFGT,    WA_FORMAT, COMPARE, RVW, {WF})
`DEFINE_WA_INSTRUCTION(WMFGE,    WA_FORMAT, COMPARE, RVW, {WF})
`DEFINE_WA_INSTRUCTION(WFCLASS_W,WS2_FORMAT, COMPARE, RVW)
`DEFINE_WA_INSTRUCTION(WFMERGE,  WA_FORMAT, ARITHMETIC, RVW, {WFM})
`DEFINE_WA_INSTRUCTION(WFMV,     WA_FORMAT, ARITHMETIC, RVW, {WF})

// Matrix conversion instructions
`DEFINE_WA_INSTRUCTION(WFCVT_XU_F_W,     WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFCVT_X_F_W,      WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFCVT_F_XU_W,     WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFCVT_F_X_W,      WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFWCVT_XU_F_W,    WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFWCVT_X_F_W,     WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFWCVT_F_XU_W,    WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFWCVT_F_X_W,     WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFWCVT_F_F_W,     WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFNCVT_XU_F_W,    WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFNCVT_X_F_W,     WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFNCVT_F_XU_W,    WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFNCVT_F_X_W,     WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFNCVT_F_F_W,     WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFNCVT_ROD_F_F_W, WS2_FORMAT, ARITHMETIC, RVW)

// Matrix reduction instruction
`DEFINE_WA_INSTRUCTION(WREDSUM_WS,    WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WREDMAXU_WS,   WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WREDMAX_WS,    WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WREDMINU_WS,   WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WREDMIN_WS,    WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WREDAND_WS,    WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WREDOR_WS,     WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WREDXOR_WS,    WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WWREDSUMU_WS,  WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WWREDSUM_WS,   WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFREDOSUM_WS,  WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFREDSUM_WS,   WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFREDMAX_WS,   WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFWREDOSUM_WS, WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFWREDSUM_WS,  WA_FORMAT, ARITHMETIC, RVW)

// Matrix mask instruction
`DEFINE_WA_INSTRUCTION(WMAND_MM,    WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WMNAND_MM,   WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WMANDNOT_MM, WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WMXOR_MM,    WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WMOR_MM,     WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WMNOR_MM,    WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WMORNOT_MM,  WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WMXNOR_MM,   WA_FORMAT, ARITHMETIC, RVW)

`DEFINE_WA_INSTRUCTION(WPOPC_M,   WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFIRST_M,  WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WMSBF_M,   WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WMSIF_M,   WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WMSOF_M,   WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WIOTA_M,   WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WID_W,     WS2_FORMAT, ARITHMETIC, RVW)

// Matrix permutation instruction
`DEFINE_WA_INSTRUCTION(WMV_X_S,  WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WMV_S_X,  WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFMV_F_S, WA_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WFMV_S_F, WA_FORMAT, ARITHMETIC, RVW)

`DEFINE_WA_INSTRUCTION(WSLIDEUP,    WA_FORMAT, ARITHMETIC, RVW, {VI,WX})
`DEFINE_WA_INSTRUCTION(WSLIDEDOWN,  WA_FORMAT, ARITHMETIC, RVW, {VI,WX})
`DEFINE_WA_INSTRUCTION(WSLIDE1UP,   WA_FORMAT, ARITHMETIC, RVW, {WX})
`DEFINE_WA_INSTRUCTION(WSLIDE1DOWN, WA_FORMAT, ARITHMETIC, RVW, {WX})
`DEFINE_WA_INSTRUCTION(WRGATHER,    WA_FORMAT, ARITHMETIC, RVW, {WW,WX,VI})
`DEFINE_WA_INSTRUCTION(WCOMPRESS,   WA_FORMAT, ARITHMETIC, RVW, {VM})

`DEFINE_WA_INSTRUCTION(WMV1R_W, WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WMV2R_W, WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WMV4R_W, WS2_FORMAT, ARITHMETIC, RVW)
`DEFINE_WA_INSTRUCTION(WMV8R_W, WS2_FORMAT, ARITHMETIC, RVW)

// -------------------------------------------------------------------------
//  Section 7. Matrix Loads and Stores
// -------------------------------------------------------------------------
// Section 7.4 - Matrix Unit-Stride Instructions
`DEFINE_WA_INSTRUCTION(WLE_W, WL_FORMAT, LOAD, RVW)
`DEFINE_WA_INSTRUCTION(WSE_W, WS_FORMAT, STORE, RVW)
// Section 7.5 - Matrix Strided Instructions
`DEFINE_WA_INSTRUCTION(WLSE_W, WLS_FORMAT, LOAD, RVW)
`DEFINE_WA_INSTRUCTION(WSSE_W, WSS_FORMAT, STORE, RVW)
// Section 7.6 - Matrix Indexed Instructions
`DEFINE_WA_INSTRUCTION(WLXEI_W, WLX_FORMAT, LOAD, RVW)
`DEFINE_WA_INSTRUCTION(WSXEI_W, WSX_FORMAT, STORE, RVW)
`DEFINE_WA_INSTRUCTION(WSUXEI_W, WSX_FORMAT, STORE, RVW)
// Section 7.7 - Matrix Unit-Stride Fault-Only-First Loads
`DEFINE_WA_INSTRUCTION(WLEFF_W, WL_FORMAT, LOAD, RVW)
// Section 7.8 - Matrix Load/Store Segment Instructions (Zvlsseg)
// 7.8.1. Matrix Unit Strided Segment Loads and Stores
`DEFINE_WA_INSTRUCTION(WLSEGE_W, WL_FORMAT, LOAD, RVW, {}, "zwlsseg")
`DEFINE_WA_INSTRUCTION(WSSEGE_W, WS_FORMAT, STORE, RVW, {}, "zwlsseg")
`DEFINE_WA_INSTRUCTION(WLSEGEFF_W, WL_FORMAT, LOAD, RVW, {}, "zwlsseg")
// 7.8.2. Matrix Strided Segment Loads and Stores
`DEFINE_WA_INSTRUCTION(WLSSEGE_W, WLS_FORMAT, LOAD, RVW, {}, "zwlsseg")
`DEFINE_WA_INSTRUCTION(WSSSEGE_W, WSS_FORMAT, STORE, RVW, {}, "zwlsseg")
// 7.8.3. Matrix Indexed Segment Loads and Stores
`DEFINE_WA_INSTRUCTION(WLXSEGEI_W, WLX_FORMAT, LOAD, RVW, {}, "zwlsseg")
`DEFINE_WA_INSTRUCTION(WSXSEGEI_W, WSX_FORMAT, STORE, RVW, {}, "zwlsseg")
`DEFINE_WA_INSTRUCTION(WSUXSEGEI_W, WSX_FORMAT, STORE, RVW, {}, "zwlsseg")

// -------------------------------------------------------------------------
//  Section 8. Matrix AMO Operations (Zvamo)
// -------------------------------------------------------------------------
// EEW matrix AMOs
`DEFINE_WA_INSTRUCTION(WAMOSWAPE_W, VAMO_FORMAT, AMO, RVW, {}, "zwamo")
`DEFINE_WA_INSTRUCTION(WAMOADDE_W, VAMO_FORMAT, AMO, RVW, {}, "zwamo")
`DEFINE_WA_INSTRUCTION(WAMOXORE_W, VAMO_FORMAT, AMO, RVW, {}, "zwamo")
`DEFINE_WA_INSTRUCTION(WAMOANDE_W, VAMO_FORMAT, AMO, RVW, {}, "zwamo")
`DEFINE_WA_INSTRUCTION(WAMOORE_W, VAMO_FORMAT, AMO, RVW, {}, "zwamo")
`DEFINE_WA_INSTRUCTION(WAMOMINE_W, VAMO_FORMAT, AMO, RVW, {}, "zwamo")
`DEFINE_WA_INSTRUCTION(WAMOMAXE_W, VAMO_FORMAT, AMO, RVW, {}, "zwamo")
`DEFINE_WA_INSTRUCTION(WAMOMINUE_W, VAMO_FORMAT, AMO, RVW, {}, "zwamo")
`DEFINE_WA_INSTRUCTION(WAMOMAXUE_W, VAMO_FORMAT, AMO, RVW, {}, "zwamo")
