/*
 * Copyright 2019 Google LLC
 * Copyright 2019 Mellanox Technologies Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Remaining bitmanip instructions of draft v.0.93 not ratified in v.1.00 (Zba, Zbb, Zbc, Zbs).

// LOGICAL instructions
`DEFINE_B_INSTRUCTION(GORC,     R_FORMAT, LOGICAL, RV32B)
`DEFINE_B_INSTRUCTION(GORCI,    I_FORMAT, LOGICAL, RV32B, UIMM)
`DEFINE_B_INSTRUCTION(CMIX,    R4_FORMAT, LOGICAL, RV32B)
`DEFINE_B_INSTRUCTION(CMOV,    R4_FORMAT, LOGICAL, RV32B)
`DEFINE_B_INSTRUCTION(PACK,     R_FORMAT, LOGICAL, RV32B)
`DEFINE_B_INSTRUCTION(PACKU,    R_FORMAT, LOGICAL, RV32B)
`DEFINE_B_INSTRUCTION(PACKH,    R_FORMAT, LOGICAL, RV32B)
`DEFINE_B_INSTRUCTION(XPERM_N,  R_FORMAT, LOGICAL, RV32B)
`DEFINE_B_INSTRUCTION(XPERM_B,  R_FORMAT, LOGICAL, RV32B)
`DEFINE_B_INSTRUCTION(XPERM_H,  R_FORMAT, LOGICAL, RV32B)
// SHIFT intructions
`DEFINE_B_INSTRUCTION(SLO,    R_FORMAT, SHIFT, RV32B)
`DEFINE_B_INSTRUCTION(SRO,    R_FORMAT, SHIFT, RV32B)
`DEFINE_B_INSTRUCTION(SLOI,   I_FORMAT, SHIFT, RV32B, UIMM)
`DEFINE_B_INSTRUCTION(SROI,   I_FORMAT, SHIFT, RV32B, UIMM)
`DEFINE_B_INSTRUCTION(GREV,   R_FORMAT, SHIFT, RV32B)
`DEFINE_B_INSTRUCTION(GREVI,  I_FORMAT, SHIFT, RV32B, UIMM)
`DEFINE_B_INSTRUCTION(FSL,   R4_FORMAT, SHIFT, RV32B)
`DEFINE_B_INSTRUCTION(FSR,   R4_FORMAT, SHIFT, RV32B)
`DEFINE_B_INSTRUCTION(FSRI,   I_FORMAT, SHIFT, RV32B, UIMM)
// ARITHMETIC intructions
`DEFINE_B_INSTRUCTION(CRC32_B,     R_FORMAT, ARITHMETIC, RV32B)
`DEFINE_B_INSTRUCTION(CRC32_H,     R_FORMAT, ARITHMETIC, RV32B)
`DEFINE_B_INSTRUCTION(CRC32_W,     R_FORMAT, ARITHMETIC, RV32B)
`DEFINE_B_INSTRUCTION(CRC32C_B,    R_FORMAT, ARITHMETIC, RV32B)
`DEFINE_B_INSTRUCTION(CRC32C_H,    R_FORMAT, ARITHMETIC, RV32B)
`DEFINE_B_INSTRUCTION(CRC32C_W,    R_FORMAT, ARITHMETIC, RV32B)
`DEFINE_B_INSTRUCTION(SHFL,        R_FORMAT, ARITHMETIC, RV32B)
`DEFINE_B_INSTRUCTION(UNSHFL,      R_FORMAT, ARITHMETIC, RV32B)
`DEFINE_B_INSTRUCTION(SHFLI,       I_FORMAT, ARITHMETIC, RV32B, UIMM)
`DEFINE_B_INSTRUCTION(UNSHFLI,     I_FORMAT, ARITHMETIC, RV32B, UIMM)
`DEFINE_B_INSTRUCTION(BCOMPRESS,   R_FORMAT, ARITHMETIC, RV32B)
`DEFINE_B_INSTRUCTION(BDECOMPRESS, R_FORMAT, ARITHMETIC, RV32B)
`DEFINE_B_INSTRUCTION(BFP,         R_FORMAT, ARITHMETIC, RV32B)
