/*
 * Copyright 2019 Google LLC
 * Copyright 2019 Mellanox Technologies Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Remaining bitmanip instructions of draft v.0.93 not ratified in v.1.00 (Zba, Zbb, Zbc, Zbs).

// ARITHMETIC intructions
`DEFINE_B_INSTRUCTION(BMATOR,       R_FORMAT, ARITHMETIC, RV64B)
`DEFINE_B_INSTRUCTION(BMATXOR,      R_FORMAT, ARITHMETIC, RV64B)
`DEFINE_B_INSTRUCTION(BMATFLIP,     R_FORMAT, ARITHMETIC, RV64B)
`DEFINE_B_INSTRUCTION(CRC32_D,      R_FORMAT, ARITHMETIC, RV64B)
`DEFINE_B_INSTRUCTION(CRC32C_D,     R_FORMAT, ARITHMETIC, RV64B)
`DEFINE_B_INSTRUCTION(SHFLW,        R_FORMAT, ARITHMETIC, RV64B)
`DEFINE_B_INSTRUCTION(UNSHFLW,      R_FORMAT, ARITHMETIC, RV64B)
`DEFINE_B_INSTRUCTION(BCOMPRESSW,   R_FORMAT, ARITHMETIC, RV64B)
`DEFINE_B_INSTRUCTION(BDECOMPRESSW, R_FORMAT, ARITHMETIC, RV64B)
`DEFINE_B_INSTRUCTION(BFPW,         R_FORMAT, ARITHMETIC, RV64B)
// SHIFT intructions
`DEFINE_B_INSTRUCTION(SLOW,    R_FORMAT, SHIFT, RV64B)
`DEFINE_B_INSTRUCTION(SROW,    R_FORMAT, SHIFT, RV64B)
`DEFINE_B_INSTRUCTION(SLOIW,   I_FORMAT, SHIFT, RV64B, UIMM)
`DEFINE_B_INSTRUCTION(SROIW,   I_FORMAT, SHIFT, RV64B, UIMM)
`DEFINE_B_INSTRUCTION(GREVW,   R_FORMAT, SHIFT, RV64B)
`DEFINE_B_INSTRUCTION(GREVIW,  I_FORMAT, SHIFT, RV64B, UIMM)
`DEFINE_B_INSTRUCTION(FSLW,   R4_FORMAT, SHIFT, RV64B)
`DEFINE_B_INSTRUCTION(FSRW,   R4_FORMAT, SHIFT, RV64B)
`DEFINE_B_INSTRUCTION(FSRIW,   I_FORMAT, SHIFT, RV64B, UIMM)
// LOGICAL instructions
`DEFINE_B_INSTRUCTION(GORCW,   R_FORMAT, LOGICAL, RV64B)
`DEFINE_B_INSTRUCTION(GORCIW,  I_FORMAT, LOGICAL, RV64B, UIMM)
`DEFINE_B_INSTRUCTION(PACKW,   R_FORMAT, LOGICAL, RV64B)
`DEFINE_B_INSTRUCTION(PACKUW,  R_FORMAT, LOGICAL, RV64B)
`DEFINE_B_INSTRUCTION(XPERM_W, R_FORMAT, LOGICAL, RV64B)
