/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

`DEFINE_C_INSTRUCTION(C_LW,       CL_FORMAT, LOAD, RV32C, UIMM)
`DEFINE_C_INSTRUCTION(C_SW,       CS_FORMAT, STORE, RV32C, UIMM)
`DEFINE_C_INSTRUCTION(C_LWSP,     CI_FORMAT, LOAD, RV32C, UIMM)
`DEFINE_C_INSTRUCTION(C_SWSP,     CSS_FORMAT, STORE, RV32C, UIMM)
`DEFINE_C_INSTRUCTION(C_ADDI4SPN, CIW_FORMAT, ARITHMETIC, RV32C, NZUIMM)
`DEFINE_C_INSTRUCTION(C_ADDI,     CI_FORMAT, ARITHMETIC, RV32C, NZIMM)
`DEFINE_C_INSTRUCTION(C_ADDI16SP, CI_FORMAT, ARITHMETIC, RV32C, NZIMM)
`DEFINE_C_INSTRUCTION(C_LI,       CI_FORMAT, ARITHMETIC, RV32C)
`DEFINE_C_INSTRUCTION(C_LUI,      CI_FORMAT, ARITHMETIC, RV32C, NZIMM)
`DEFINE_C_INSTRUCTION(C_SUB,      CA_FORMAT, ARITHMETIC, RV32C)
`DEFINE_C_INSTRUCTION(C_ADD,      CR_FORMAT, ARITHMETIC, RV32C)
`DEFINE_C_INSTRUCTION(C_NOP,      CI_FORMAT, ARITHMETIC, RV32C)
`DEFINE_C_INSTRUCTION(C_MV,       CR_FORMAT, ARITHMETIC, RV32C)
`DEFINE_C_INSTRUCTION(C_ANDI,     CB_FORMAT, LOGICAL, RV32C)
`DEFINE_C_INSTRUCTION(C_XOR,      CA_FORMAT, LOGICAL, RV32C)
`DEFINE_C_INSTRUCTION(C_OR,       CA_FORMAT, LOGICAL, RV32C)
`DEFINE_C_INSTRUCTION(C_AND,      CA_FORMAT, LOGICAL, RV32C)
`DEFINE_C_INSTRUCTION(C_BEQZ,     CB_FORMAT, BRANCH, RV32C)
`DEFINE_C_INSTRUCTION(C_BNEZ,     CB_FORMAT, BRANCH, RV32C)
`DEFINE_C_INSTRUCTION(C_SRLI,     CB_FORMAT, SHIFT, RV32C, NZUIMM)
`DEFINE_C_INSTRUCTION(C_SRAI,     CB_FORMAT, SHIFT, RV32C, NZUIMM)
`DEFINE_C_INSTRUCTION(C_SLLI,     CI_FORMAT, SHIFT, RV32C, NZUIMM)
`DEFINE_C_INSTRUCTION(C_J,        CJ_FORMAT, JUMP, RV32C)
`DEFINE_C_INSTRUCTION(C_JAL,      CJ_FORMAT, JUMP, RV32C)
`DEFINE_C_INSTRUCTION(C_JR,       CR_FORMAT, JUMP, RV32C)
`DEFINE_C_INSTRUCTION(C_JALR,     CR_FORMAT, JUMP, RV32C)
`DEFINE_C_INSTRUCTION(C_EBREAK,   CI_FORMAT, SYSTEM, RV32C)
