pandoc riscv-greencard.md -o riscv-greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc base/rv-e/greencard.md -o base/rv-e/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc base/rv-i/greencard.md -o base/rv-i/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc base/rv-o/greencard.md -o base/rv-o/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc standard/rv-a/greencard.md -o standard/rv-a/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc standard/rv-c/greencard.md -o standard/rv-c/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc standard/rv-m/greencard.md -o standard/rv-m/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc specific/Algebra/rv-v/greencard.md -o specific/Algebra/rv-v/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc specific/Algebra/rv-w/greencard.md -o specific/Algebra/rv-w/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc specific/Algebra/rv-y/greencard.md -o specific/Algebra/rv-y/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc specific/Arithmetic/rv-d/greencard.md -o specific/Arithmetic/rv-d/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc specific/Arithmetic/rv-f/greencard.md -o specific/Arithmetic/rv-f/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc specific/Arithmetic/rv-q/greencard.md -o specific/Arithmetic/rv-q/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc specific/Cryptography/rv-vk/greencard.md -o specific/Cryptography/rv-vk/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc specific/Cryptography/rv-wk/greencard.md -o specific/Cryptography/rv-wk/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc specific/Cryptography/rv-xk/greencard.md -o specific/Cryptography/rv-xk/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc specific/Cryptography/rv-yk/greencard.md -o specific/Cryptography/rv-yk/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc specific/Parallelism/rv-b/greencard.md -o specific/Parallelism/rv-b/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc specific/Parallelism/rv-n/greencard.md -o specific/Parallelism/rv-n/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc specific/Parallelism/rv-p/greencard.md -o specific/Parallelism/rv-p/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc specific/Parallelism/rv-t/greencard.md -o specific/Parallelism/rv-t/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc specific/Privilege/rv-h/greencard.md -o specific/Privilege/rv-h/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc specific/Privilege/rv-m/greencard.md -o specific/Privilege/rv-m/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc specific/Privilege/rv-s/greencard.md -o specific/Privilege/rv-s/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
pandoc specific/Privilege/rv-u/greencard.md -o specific/Privilege/rv-u/greencard.pdf --pdf-engine=xelatex -V papersize=A3 -V geometry:margin=1cm
